### PR TITLE
Click patient's name to view additional information

### PR DESCRIPTION
**Pull request by nikoskiouris**
You can click on the patient's name to view additional information

### CODE REVIEW

**Comment by Alik-da-Geek** [comment]
Looks great! Thank for changing the comments too to make this more readable ;)

**Comment by Nadir-Lafayette** [comment]
it looked like everything was good to me as well.

**Comment by nikoskiouris** [comment]
Thanks gentlemen

**Comment by hwuiwon** [comment]
Amazing

**Review by Alik-da-Geek — COMMENTED** [review]
Nice work, looks good

**Comment by zakass** [comment]
Perfect work Niko.

**Comment by astt115** [comment]
Very helpful addition. Bet it will prove to be insanely helpful to doctors in the near future.

**Pull request merged**
